"""Add stream marker tables

Revision ID: 26b48f49a37c
Revises: 9a8047116048
Create Date: 2023-02-07 17:32:32.010005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b48f49a37c'
down_revision = '9a8047116048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marker_datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('stream_key_id', sa.String(length=36), nullable=True),
    sa.Column('stream_key_nick', sa.String(length=100), nullable=True),
    sa.Column('stream_key_dicord_id', sa.BigInteger(), nullable=True),
    sa.Column('video_id', sa.String(length=15), nullable=True),
    sa.Column('offset_secs', sa.Integer(), nullable=True),
    sa.Column('marker_text', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_marker')
    # ### end Alembic commands ###
