"""initial migration

Revision ID: 9a8047116048
Revises: 
Create Date: 2023-02-07 01:49:23.676203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8047116048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streamer_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_key_id', sa.String(length=36), nullable=True),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('info_text', sa.Unicode(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_key_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streamer_info')
    # ### end Alembic commands ###
